#This file is for demonstration purposes only. Please, don't use this image for production

# Use existing fedora 22 image as the base
FROM fedora:22

MAINTAINER Rafael Benevides <benevides@redhat.com>

# Run update
RUN dnf -y update
